'use strict';

const ERROR = {
  'NOT_FOUND': 'NOT_FOUND',
  'INTERNAL_ERROR': 'INTERNAL_ERROR',
  'CONFLICT': 'CONFLICT',
  'EXPECTATION_FAILED': 'EXPECTATION_FAILED',
  'UNAUTHORIZED': 'UNAUTHORIZED'
};

module.exports = ERROR;
